import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NextAuthProvider } from "@/providers/next-auth-provider";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Architect Room",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.className} dark`}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
